### ISSUE TITLE
URL to makes.org expired certificate

### ISSUE THREAD

**Issue by maykonchagas** [gideonthomas/offline-icebreakers#3]
Hi Gideon,

Another issue. An URL to an Thimble activities point it to makes.org, but the certficate was expired, returning a 500 error code.
This is the URL: https://dajbelshaw.makes.org/thimble/MTk0NDI1Njc2OA==/html-corners
Activity 2: session02-html-thimble-tag-puzzle.html

Thanks!

**Comment by gideonthomas** [comment]
Hi @mchagas I updated the link in all three tools (Thimble, Github and Google Docs) to reflect the new url to the HTML Corners project.

Here is the link that we're using instead of (https://dajbelshaw.makes.org/thimble/MTk0NDI1Njc2OA==/html-corners): https://thimbleprojects.org/mozillalearning/138866/

**Comment by maykonchagas** [comment]
Thanks Gideon!
